create table expression
(
    id         bigint generated by default as identity,
    nominative varchar(255),
    genitive   varchar(255),
    accusative varchar(255),
    gender     varchar(255),
    primary key (id)
);

create table topic
(
    id      bigint generated by default as identity,
    name_id bigint,
    primary key (id)
);

create table item
(
    id       bigint generated by default as identity,
    topic_id bigint,
    primary key (id)
);

create table property
(
    id               bigint generated by default as identity,
    content          varchar(1024),
    property_type_id bigint,
    item_id          bigint,
    primary key (id)
);

create table property_type
(
    id                       bigint generated by default as identity,
    name_id                  bigint,
    uniqueness               varchar(255),
    question_ending_template varchar(255),
    media_type               varchar(255),
    priority                 varchar(255),
    primary key (id)
);

alter table topic
    add constraint fk_topic_expression foreign key (name_id) references expression;
alter table property_type
    add constraint fk_property_type_expression foreign key (name_id) references expression;
alter table item
    add constraint fk_resource_topic foreign key (topic_id) references topic;
alter table property
    add constraint fk_property_item foreign key (item_id) references item;
alter table property
    add constraint fk_property_property_type foreign key (property_type_id) references property_type;